// API endpoint for downloading YouTube video audio
// Uses yt-dlp to extract audio from YouTube videos

import { handleCORS, setCORSHeaders } from './cors.js';
import { exec } from 'child_process';
import { promisify } from 'util';
import { createWriteStream, unlinkSync, existsSync } from 'fs';
import { join } from 'path';
import { tmpdir } from 'os';
import fetchModule from 'node-fetch';
import {
  requireSessionEmail
} from './processing-enforcement.js';
import {
  resolveTraceId,
  sendTranscriptError,
  sendTranscriptSuccess,
  sendTranscriptErrorFromLegacy,
  userMessageForCode
} from './transcript-errors.js';
import { parseYouTubeVideoId, normalizeYouTubeWatchUrl, stripTrackingQueryParams } from './media-url.js';
import { resolveYtDlpPath, runYtDlpRobust, classifyYtDlpError } from './ytdlp-robust.js';

const execAsync = promisify(exec);

export default async function handler(req, res) {
  // Handle CORS
  const corsHandled = handleCORS(req, res);
  if (corsHandled) return;

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const userEmail = requireSessionEmail(req, res);
  if (!userEmail) return;

  const traceId = resolveTraceId(req);
  console.log('[transcript-start]', { traceId, route: 'youtube', email: userEmail });

  try {
    const { videoId, url } = req.body;

    if (!videoId && !url) {
      return sendTranscriptError(res, {
        statusCode: 400,
        errorCode: 'INVALID_URL',
        message: userMessageForCode('INVALID_URL'),
        retryable: false,
        traceId,
        stage: 'youtube'
      });
    }

    const cleanedUrl = url ? stripTrackingQueryParams(url) : '';
    let finalVideoId = videoId || (cleanedUrl ? parseYouTubeVideoId(cleanedUrl) : null);
    if (!finalVideoId && cleanedUrl) {
      console.log('[yt-shorts]', { traceId, url: cleanedUrl, parsed: null });
    } else if (cleanedUrl && /\/shorts\//i.test(cleanedUrl)) {
      console.log('[yt-shorts]', { traceId, url: cleanedUrl, videoId: finalVideoId, normalized: normalizeYouTubeWatchUrl(cleanedUrl) });
    }

    if (!finalVideoId) {
      const errorCode = cleanedUrl && /\/shorts\//i.test(cleanedUrl) ? 'SHORTS_PARSE_ERROR' : 'INVALID_URL';
      return sendTranscriptError(res, {
        statusCode: 400,
        errorCode,
        message: userMessageForCode(errorCode),
        retryable: false,
        traceId,
        stage: 'youtube'
      });
    }

    console.log('[transcript-download]', { traceId, videoId: finalVideoId });
    console.log(`YOUTUBE: Extracting audio for video ID: ${finalVideoId}`);

    const ytDlpPath = await resolveYtDlpPath();

    // Create temporary file path
    const tempDir = tmpdir();
    const audioFilePath = join(tempDir, `youtube_${finalVideoId}_${Date.now()}.mp3`);

    try {
      // Extract audio using yt-dlp
      // Format: bestaudio/best - best audio quality available
      // Extract audio and convert to mp3
      const youtubeUrl = `https://www.youtube.com/watch?v=${finalVideoId}`;
      
      console.log(`YOUTUBE: Downloading audio from: ${youtubeUrl}`);
      
      // First, get video metadata to detect language and available subtitles
      console.log('YOUTUBE: Getting video metadata...');
      let detectedLanguage = null;
      let availableSubtitles = {};
      let autoGeneratedSubtitles = {};
      let videoTitle = null;
      let videoDuration = null;
      
      try {
        const { stdout: metadataStdout, stderr: metadataStderr } = await runYtDlpRobust({
          ytDlpPath,
          baseArgs: ['--no-playlist', '--dump-json', '--no-download'],
          url: youtubeUrl,
          requestKey: userEmail,
          traceId,
          mode: 'metadata'
        });
        
        if (metadataStderr) {
          console.warn('YOUTUBE: Metadata command stderr:', metadataStderr.substring(0, 200));
        }
        
        console.log(`YOUTUBE: Metadata stdout length: ${metadataStdout.length}`);
        const metadata = JSON.parse(metadataStdout);
        
        console.log('YOUTUBE: Metadata keys:', Object.keys(metadata || {}));
        console.log('YOUTUBE: Metadata.title exists:', !!metadata.title);
        console.log('YOUTUBE: Metadata.title value:', metadata.title);
        
        // Get video title
        if (metadata.title) {
          videoTitle = metadata.title;
          console.log(`YOUTUBE: Video title extracted: ${videoTitle}`);
        } else {
          console.warn('YOUTUBE: No title found in metadata');
          console.warn('YOUTUBE: Full metadata (first 500 chars):', JSON.stringify(metadata).substring(0, 500));
        }
        
        // Get video duration
        if (metadata.duration) {
          videoDuration = metadata.duration;
          console.log(`YOUTUBE: Video duration: ${videoDuration} seconds`);
        }
        
        // Try to get language from metadata
        if (metadata.language) {
          detectedLanguage = metadata.language;
          console.log(`YOUTUBE: Detected language from metadata: ${detectedLanguage}`);
        }
        
        // Get available subtitles (both manual and auto-generated)
        if (metadata.subtitles) {
          availableSubtitles = metadata.subtitles;
          console.log(`YOUTUBE: Available manual subtitles:`, Object.keys(availableSubtitles));
        }
        
        if (metadata.automatic_captions) {
          autoGeneratedSubtitles = metadata.automatic_captions;
          console.log(`YOUTUBE: Available auto-generated subtitles:`, Object.keys(autoGeneratedSubtitles));
        }

        const { resolveDetectedLanguage } = await import('./youtube-subtitle-lang.js');
        detectedLanguage = resolveDetectedLanguage(
          detectedLanguage,
          Object.keys(autoGeneratedSubtitles),
          Object.keys(availableSubtitles)
        );
        if (detectedLanguage) {
          console.log(`YOUTUBE: Resolved content language: ${detectedLanguage}`);
        }
      } catch (metadataError) {
        console.warn('YOUTUBE: Could not get metadata, will auto-detect:', metadataError.message);
      }

      // Use yt-dlp to extract audio
      // -x: extract audio only
      // --audio-format mp3: convert to mp3
      // -o: output file
      const { stdout, stderr } = await runYtDlpRobust({
        ytDlpPath,
        baseArgs: ['--no-playlist', '--no-warnings', '-x', '--audio-format', 'mp3', '--audio-quality', '0', '-o', audioFilePath],
        url: youtubeUrl,
        requestKey: userEmail,
        traceId,
        mode: 'audio_extract'
      });

      console.log(`YOUTUBE: Download complete, stdout: ${stdout.substring(0, 200)}`);
      if (stderr) {
        console.warn(`YOUTUBE: stderr: ${stderr.substring(0, 200)}`);
      }

      // Check if file exists
      if (!existsSync(audioFilePath)) {
        // Sometimes yt-dlp saves with different extension, try to find it
        const fs = await import('fs');
        const files = fs.readdirSync(tempDir);
        const matchingFile = files.find(f => f.includes(finalVideoId));
        
        if (matchingFile) {
          const actualPath = join(tempDir, matchingFile);
          console.log(`YOUTUBE: Found file with different name: ${actualPath}`);
          
          // Read file and send as base64
          const audioBuffer = fs.readFileSync(actualPath);
          
          // Clean up
          try {
            fs.unlinkSync(actualPath);
          } catch (cleanupErr) {
            console.warn('YOUTUBE: Failed to cleanup temp file:', cleanupErr);
          }
          
          const base64Audio = audioBuffer.toString('base64');
          const mimeType = 'audio/mpeg';
          
          setCORSHeaders(res);
          return res.status(200).json({
            audioUrl: `data:${mimeType};base64,${base64Audio}`,
            videoId: finalVideoId,
            format: 'mp3'
          });
        } else {
          throw new Error('Audio file not found after download');
        }
      }

      // Read the audio file
      const fs = await import('fs');
      const audioBuffer = fs.readFileSync(audioFilePath);
      
      // Note: Whisper API has 25MB limit, but we'll process large files by chunks
      // For now, we'll allow up to 100MB and process in chunks if needed
      const maxSize = 100 * 1024 * 1024; // 100MB (will be chunked if > 25MB)
      if (audioBuffer.length > maxSize) {
        // Clean up
        try {
          fs.unlinkSync(audioFilePath);
        } catch (cleanupErr) {
          console.warn('YOUTUBE: Failed to cleanup temp file:', cleanupErr);
        }
        
        return sendTranscriptError(res, {
          statusCode: 413,
          errorCode: 'FILE_TOO_LARGE',
          message: `This clip is too large for one run (${(audioBuffer.length / 1024 / 1024).toFixed(1)} MB). Maximum ${maxSize / 1024 / 1024} MB.`,
          retryable: false,
          traceId,
          phase: 'youtube-download'
        });
      }
      
      // If file is larger than 25MB, we'll need to chunk it
      // But for now, we'll return it and let the transcribe endpoint handle chunking
      if (audioBuffer.length > 25 * 1024 * 1024) {
        console.log(`YOUTUBE: File is ${(audioBuffer.length / 1024 / 1024).toFixed(2)}MB, will be processed in chunks`);
      }

      // Convert to base64
      const base64Audio = audioBuffer.toString('base64');
      const mimeType = 'audio/mpeg';

      // Clean up temporary file
      try {
        fs.unlinkSync(audioFilePath);
        console.log('YOUTUBE: Temporary file cleaned up');
      } catch (cleanupErr) {
        console.warn('YOUTUBE: Failed to cleanup temp file:', cleanupErr);
      }

      console.log(`YOUTUBE: Success, audio size: ${audioBuffer.length} bytes`);

      // Try to download subtitles if available
      let subtitles = null;
      let subtitleLanguage = null;
      
      try {
        const { pickSubtitleLanguageFromMetadata } = await import('./youtube-subtitle-lang.js');
        subtitleLanguage = pickSubtitleLanguageFromMetadata({
          detectedLanguage,
          manualSubtitles: availableSubtitles,
          autoGeneratedSubtitles,
          userHint: detectedLanguage || 'en'
        });

        if (subtitleLanguage) {
          console.log(`YOUTUBE: Downloading subtitles in language: ${subtitleLanguage}`);
          
          // Download subtitle file
          try {
            await runYtDlpRobust({
              ytDlpPath,
              baseArgs: ['--no-playlist', '--write-auto-sub', '--sub-lang', subtitleLanguage, '--skip-download', '--sub-format', 'vtt', '-o', `${tempDir}/youtube_${finalVideoId}_subtitle`],
              url: youtubeUrl,
              requestKey: userEmail,
              traceId,
              mode: 'subtitle_fetch'
            });
            
            // Find the subtitle file
            const fs = await import('fs');
            const files = fs.readdirSync(tempDir);
            const subtitleFile = files.find(f => f.includes(finalVideoId) && (f.endsWith('.vtt') || f.endsWith('.srt')));
            
            if (subtitleFile) {
              const subtitlePath = join(tempDir, subtitleFile);
              const subtitleContent = fs.readFileSync(subtitlePath, 'utf8');
              subtitles = subtitleContent;
              
              // Clean up
              try {
                fs.unlinkSync(subtitlePath);
              } catch (cleanupErr) {
                console.warn('YOUTUBE: Failed to cleanup subtitle file:', cleanupErr);
              }
              
              console.log(`YOUTUBE: Successfully downloaded subtitles (${subtitleContent.length} chars)`);
            }
          } catch (subtitleError) {
            console.warn('YOUTUBE: Could not download subtitles:', subtitleError.message);
          }
        }
      } catch (subtitleErr) {
        console.warn('YOUTUBE: Error processing subtitles:', subtitleErr.message);
      }

      // Log title before returning
      console.log(`YOUTUBE: Returning title in response: ${videoTitle || 'null'}`);
      console.log(`YOUTUBE: Returning duration in response: ${videoDuration || 'null'}`);

      return sendTranscriptSuccess(res, traceId, {
        audioUrl: `data:${mimeType};base64,${base64Audio}`,
        videoId: finalVideoId,
        format: 'mp3',
        size: audioBuffer.length,
        language: detectedLanguage || null,
        subtitles: subtitles,
        subtitleLanguage: subtitleLanguage,
        availableLanguages: Object.keys(autoGeneratedSubtitles).length > 0
          ? Object.keys(autoGeneratedSubtitles)
          : Object.keys(availableSubtitles),
        title: videoTitle || null,
        duration: videoDuration || null
      });

    } catch (downloadError) {
      // Clean up on error
      try {
        const fs = await import('fs');
        if (existsSync(audioFilePath)) {
          fs.unlinkSync(audioFilePath);
        }
      } catch (cleanupErr) {
        console.warn('YOUTUBE: Failed to cleanup temp file on error:', cleanupErr);
      }

      console.error('YOUTUBE_ERROR: Download failed:', downloadError);
      
      const mapped = classifyYtDlpError(downloadError?.stderr || downloadError?.message || '');
      const legacy =
        mapped.code === 'YTDLP_VIDEO_UNAVAILABLE'
          ? 'VIDEO_UNAVAILABLE'
          : mapped.code === 'YTDLP_AUTH_REQUIRED'
            ? 'SOCIAL_LOGIN_REQUIRED'
            : mapped.code === 'YTDLP_TEMP_BLOCK'
              ? 'YTDLP_TIMEOUT'
              : 'YOUTUBE_ERROR';
      return sendTranscriptErrorFromLegacy(res, {
        statusCode: legacy === 'VIDEO_UNAVAILABLE' ? 422 : legacy === 'SOCIAL_LOGIN_REQUIRED' ? 401 : 500,
        legacyCode: legacy,
        message: mapped.message,
        traceId,
        stage: 'youtube-download'
      });
    }

  } catch (error) {
    console.error('YOUTUBE_ERROR:', { traceId, message: error?.message });
    return sendTranscriptErrorFromLegacy(res, {
      statusCode: 500,
      legacyCode: 'YOUTUBE_ERROR',
      message: error?.message,
      traceId,
      stage: 'youtube'
    });
  }
}

