import test from 'node:test';
import assert from 'node:assert/strict';
import {
  resolveDetectedLanguage,
  pickSubtitleLanguageFromMetadata
} from './youtube-subtitle-lang.js';

test('French metadata wins over English auto-caption track', () => {
  const lang = resolveDetectedLanguage('fr', ['en', 'fr-FR', 'fr'], ['fr']);
  assert.ok(String(lang).startsWith('fr'));
});

test('pickSubtitleLanguage prefers metadata French', () => {
  const picked = pickSubtitleLanguageFromMetadata({
    detectedLanguage: 'fr',
    manualSubtitles: { fr: true },
    autoGeneratedSubtitles: { en: true, fr: true }
  });
  assert.equal(picked, 'fr');
});
